classroomtools/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from randomizer import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('randomizer/', include('randomizer.urls', namespace="randomizer")),
    path('', views.index),
    url(r'^accounts/', include('allauth.urls')),
]

randomizer/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views
from randomizer.views import create_classroom_view, list_classroom_view, delete_classroom_view, update_classroom_view

app_name = "randomizer"
urlpatterns = [
    path('', views.index, name='index'),
    path('submitted', views.submitted, name='submitted'),
    path('classup/', views.get_classlist, name='classroom'),
    path('random/', views.random, name='random'),
    path('blocklist/', list_classroom_view, name='blocklist'),
    path('<int:pk>/blockDelete/', delete_classroom_view, name='blockDelete'),
    path('<int:pk>/blockUpdate/', update_classroom_view, name='blockUpdate'),

]

randomizer/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms
import django_filters

class Classroom(models.Model):
    GRADE= (
        ('8', '8'),
        ('9', '9'),
        ('10', '10'),
        ('11', '11'),
        ('12', '12'),
    )
    COURSE_NAME = (
        ('MA', 'Math'),
        ('SC', 'Science'),
        ('SS', 'Social Studies'),
        ('EN', 'English Language Arts'),
        ('AP', 'Applied Skills'),
        ('PE', 'Phys Ed'),
        ('ML', 'Modern Languages'),
        ('CE', 'Career Ed'),
        ('AR', 'Arts'),
    )
    BLOCK_NUMBER = (
        ('11', 'Block 1-1'),
        ('12', 'Block 1-2'),
        ('13', 'Block 1-3'),
        ('14', 'Block 1-4'),
        ('21', 'Block 2-1'),
        ('22', 'Block 2-2'),
        ('23', 'Block 2-3'),
        ('24', 'Block 2-4'),
    )
    class_list = models.TextField()
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    course_name = models.CharField(max_length=20, choices=COURSE_NAME)
    course_block = models.CharField(max_length=10, choices=BLOCK_NUMBER)
    grade = models.CharField(max_length=2, default='8', choices=GRADE)
    
    class Meta:
        unique_together = ('course_block', 'teacher')

    def __str__(self):
        return self.get_course_block_display()
    
    def save(self, *args, **kwargs):
        super(Classroom, self).save(*args, **kwargs)
        # overrides the default save function to parse the class list
        student_list = []
        student_list = self.class_list.split('\n')
        for line in student_list:
            line = line.strip('\r')
            all_names = line.split()
            num_names = len(all_names)
            if num_names == 2:
                last = all_names[1]
            else:
                last = ' '
            nick = all_names[0] + last[:1]
            Student.objects.create(nickname=nick, student_first=all_names[0],
                                   student_last=last, attend=True, classroom=self)

class Student(models.Model):
    #user = models.ForeignKey(teacher, on_delete=models.CASCADE, default=1)
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    student_first = models.CharField(default='John', max_length=30)
    student_last = models.CharField(default='Smith', max_length=30)
    nickname = models.CharField(default='JohnS', max_length=31)
    attend = models.BooleanField(default=True)
    do_not_pick = models.BooleanField(default=False)
    

class StudentFilter(django_filters.FilterSet):
    class Meta:
        model = Student
        fields = ['classroom__course_block']

randomizer/forms.py
from django import forms
from django.forms import ModelForm
from .models import Classroom
from django.core.exceptions import ValidationError

class ClassroomForm(ModelForm):
    class Meta:
        model = Classroom
        fields = ['course_name', 'grade', 'course_block','class_list']
        
    def __init__(self, *args, **kwargs):
        super(ClassroomForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control'})
            
    def validate_unique(self):
        try:
            self.instance.validate_unique(exclude=None)
        except ValidationError as e:
            self._update_errors(e)
          
##    def clean_course_block(self):
##        course_block = self.cleaned_data['course_block']
##        if Classroom.objects.filter(course_block=course_block).exclude(pk=self.instance.pk).exists():
##            raise ValidationError('This course block is already used.')
##        return course_block

class DeleteForm(ModelForm):
    class Meta:
        model = Classroom
        fields = ['course_block']
        

    

randomizer/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader, Context
from django.shortcuts import get_object_or_404, Http404, render, get_list_or_404
#from django.forms import ModelForm
from django.views.generic.edit import CreateView, FormView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.utils import timezone
from django.urls import reverse, reverse_lazy
from django.core.exceptions import ObjectDoesNotExist
from django.core import serializers
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

from django.shortcuts import render

import json
from .models import Classroom, Student, StudentFilter
from .forms import ClassroomForm, DeleteForm

def index(request):
    nickname_list = Classroom.objects.order_by('nickname')
    context = {'nickname_list': nickname_list}
    return render(request, 'randomizer/index.html', context)

@login_required
def submitted(request):
    return render(request, 'randomizer/submitted.html')

class ClassroomCreateView(LoginRequiredMixin, CreateView):
    #login_url = '/login/'
    redirect_field_name = 'redirect_to'
    model = Classroom
    form_class = ClassroomForm
    
    #send user to ClassroomForm to initialise custom field
##    def get_form_kwargs(self):
##        kwargs = super(ClassroomCreateView, self).get_form_kwargs()
##        kwargs['teacher'] = self.request.user
##        return kwargs
    
    def form_valid(self, form):
        f = form.save(commit=False)
        print(form.cleaned_data['class_block'])
        f.teacher = self.request.user
        f.save()            
        return super().form_valid(form)
       
    def get_success_url(self):
        return reverse('classroom:blocklist')
    
create_classroom_view = ClassroomCreateView.as_view()

def get_classlist(request):
    if request.method == 'POST':
        form = ClassroomForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.teacher = request.user
            f.save()  
            return HttpResponseRedirect('/randomizer/blocklist')

    else:
        form = ClassroomForm()

    return render(request, 'randomizer/classroom_form.html', {'form': form})

class BlockListView(LoginRequiredMixin, ListView):
    #login_url = 'accounts/login/'
    redirect_field_name = 'redirect_to'
    model= Classroom

    def get_context_data(self, **kwargs):
        context = super(BlockListView, self).get_context_data(**kwargs)
        classroom_blocks = Classroom.objects.filter(teacher=self.request.user)
        context = {'classroom_blocks': classroom_blocks}
        return context

list_classroom_view = BlockListView.as_view()

class BlockDeleteView(LoginRequiredMixin, DeleteView):
    #login_url = '/login/'
    redirect_field_name = 'redirect_to'
    model = Classroom
    success_url = reverse_lazy('randomizer:blocklist')

delete_classroom_view = BlockDeleteView.as_view()

class BlockUpdateView(LoginRequiredMixin, UpdateView):
    #login_url = '/login/'
    #redirect_field_name = 'redirect_to'    
    model = Classroom
    fields = ['class_list']
    #fields = ['course_name', 'course_block', 'class_list']
    success_url = reverse_lazy('randomizer:blocklist')
    
update_classroom_view = BlockUpdateView.as_view()

@login_required
def random(request):
    classroom = Classroom.objects.filter(teacher=request.user).order_by('course_block')
    classblock = request.GET.get('class_block')
    cblock = Classroom.objects.all().filter(course_block=classblock)
    cblocknum = cblock.count()
    students = Student.objects.all().filter(classroom__course_block=classblock)
    nicknames = [s.nickname for s in students]
    data = serializers.serialize("json", students, fields = ("nickname", "attend", "do_not_pick",))
    student_names = json.dumps(list(nicknames))
    context = {'students': students}
    context['classroom'] = classroom
    context['cblock'] = cblock
    context['student_names'] = student_names
    context['cblocknum'] = cblocknum
    context['data'] = data
    template = loader.get_template('randomizer/randomize.html')
    print (data)
    return render(request, 'randomizer/randomize.html', context)

@login_required
def block_delete(request, id):
    obj = get_list_or_404()
    context = {"object": obj}
    return render(request, "classroom_confirm_delete.html", context)

@login_required
def student_list(request):
    s = StudentFilter(request.GET, queryset=Student.objects.all())
    # f = AttendFilter(request.GET, queryset=Student.objects.all())
    return render(request, 'randomizer/student_list.html', {'filter': s})
    # return render(request, 'randomizer/student_list.html', {'filter2': f})

class ClassroomDetailView(LoginRequiredMixin, DetailView):
    #login_url = '/login/'
    redirect_field_name = 'redirect_to'    
    model = Classroom
    template_name = 'randomizer/random_list.html'

    def get_context_data(self, **kwargs):
        class_pk = self.kwargs['pk']
        context = super(ClassroomDetailView, self).get_context_data(**kwargs)
        students = Student.objects.filter(pk = 'class_pk')
        context['students'] = students
        return context

detail_classroom_view = ClassroomDetailView.as_view()

##def register_success(request):
##    return render_to_response('registration/success.html',)
## 
##def logout_page(request):
##    logout(request)
##    return HttpResponseRedirect('/')

randomizer/templates/randomizer/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>CES - {% block body_block %}Claim, Evidence, Significance{% endblock %}</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="http://fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans|Lato|Droid+Serif|Volkhov:400italic|Droid+Sans' rel='stylesheet' type='text/css'>
  
  <!-- JAVASCRIPT/JQUERY
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <script type="text/javascript" language="Javascript" src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.0.min.js"></script>

  <!-- Bootstrap Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme --> 
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
  <!-- local js -->
 

  <!--  local css -->
  <link rel="stylesheet" type="text/css" href="{% static 'randomizer/css/base.css' %}">
  
<!-- Favicons
	================================================== -->
<!--	<link rel="shortcut icon" href="images/favicon.ico">
	<link rel="apple-touch-icon" href="images/apple-touch-icon.png">
	<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">-->
<!--    {% block extra_css %}{% endblock extra_css %} -->

</head>
<body>


  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  {% block header %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <div class="navbar-brand">
            <a href="#"><img style="margin-top: -10px;" src={% static "randomizer/images/vsb-logo.png" %}></a>
        </div>
    </div>
    <ul class="nav navbar-nav navbar-right">
        {% if request.user.is_authenticated %}
            <li><a href={% url 'admin:index' %}>Admin</a></li>
            <li><a href={% url 'randomizer:blocklist' %}>Class List</a></li>
            <li><a href={% url 'randomizer:random' %}>Randomize</a></li>
            <li><a href="#">{{request.user.username}}</a></li>
            <li><a href={% url 'account_logout' %}>Log out</a></li>
        {% else %}
            <li><a href={% url 'randomizer:blocklist' %}>Class List</a></li>
            <li><a href="{% url 'account_login' %}" role="button">Sign In</a></li>
            <li><a href="{% url 'account_signup' %}" role="button">Sign Up</a></li>
        {% endif %}
       
    </ul>
  </div><!-- /.container-fluid -->
</nav>
  {% endblock %}
  {% block body %}{% endblock body %}
  {% block extra_js %}{% endblock extra_js %}

<!-- End Document
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
</body>
</html>

randomizer/templates/randomizer/classroom_form.html
{% extends 'randomizer/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Class/Block Entry</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
        <div class="form-group">
            <form action="{% url 'randomizer:classroom' %}" method="post">
	            {% csrf_token %}
	            {{ form.as_p }}
	            <input type="submit" class="btn btn-default" value="submit" />
            </form>
        </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4"><a href ="{% url 'randomizer:blocklist' %}" class="btn btn-default">CLICK HERE TO DELETE A BLOCK</a>
        </div>
    </div>

</div>
{% endblock %}

randomizer/templates/randomizer/classroom_list.html
{% extends 'randomizer/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="twelve columns">
            <h1>Classroom / Block List</h1>
        </div>
    </div>
    <div class="row">
            <div class="col-md-3">
                <ul>
                {% for block in classroom_blocks %}
                    <li>{{ block.get_course_block_display }}
                    <a href ="{% url 'randomizer:blockDelete' block.id %}" class="btn btn-default">DELETE</a></li>
            
                {% empty %}
                    <li>No classes set up yet.</li>
                {% endfor %}
                </ul>
            </div>
            <div class="col-md-3">
            <div class="form-group">
                <a href ="{% url 'admin:index' %}" class="btn btn-default">EDIT CLASSES</a>
                <a href ="{% url 'randomizer:classroom' %}" class="btn btn-default">ADD NEW CLASSES</a>
            </div>
            </div>
        </div>

</div>
{% endblock %}

randomizer/templates/randomizer/randomize.html
{% extends 'randomizer/base.html' %}
{% load static %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div id="djangorandom">
            {{ classroom.id }}
                <form action="{% url 'randomizer:random' %}" method="get">
                    {% csrf_token %}
                    <div class="form-group">
                        <select class="form-control" name="class_block">
                            {% for room in classroom %}
                                <option value={{ room.course_block }}>{{ room.get_course_block_display }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <span><input class="btn btn-default" type="submit" value="Submit"></span>
                </form>

            </div>
        </div>
        <div class="col-md-5">
            <div class="btn-toolbar">
                <button class="btn btn-success" type="submit" id="go">&raquo; Run</button>
                <button class="btn btn-warning" type="submit" id="stop">&raquo; Random Name</button>
                <button class="btn btn-warning" id="freezebutton">Group Size:</button>
                <select class="form-control" type="number" id="freezeGroups" style="max-width:90%;">
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="10">10</option>
                </select>
            </div>
        </div>
        <div class="col-md-4">
                <a class="btn btn-default" href="{% url 'randomizer:classroom' %}" role="button">ADD A CLASS</a>
                <a class="btn btn-default" href="{% url 'randomizer:blocklist' %}" role="button">EDIT A CLASS</a>
                
        </div>
    </div>
  
    <div class="row">
        
        <div class="col-md-1" id="student-column1"></div>
        <div class="col-md-1" id="student-column2"></div>  <!-- anchor element for js -->
        
        <div class="col-md-10">
            <div id="student-choice"></div>  <!-- anchor for student choice -->
        </div>

    </div>


</div>
{% endblock body %}

<div>
{% block extra_js %}
    <script>
        var nameArray = {{ data | safe }};
    </script>
     <script type="text/javascript" src="{% static 'randomizer/js/randomizer.js' %}"></script>
{% endblock extra_js %}
</div>

randomizer/templates/randomizer/randomizebak.html
{% extends 'randomizer/base.html' %}
{% load static %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div id="djangorandom">
            {{ classroom.id }}
                <form action="{% url 'randomizer:random' %}" method="get">
                    {% csrf_token %}
                    <div class="form-group">
                        <select class="form-control" name="class_block">
                            {% for room in classroom %}
                                <option value={{ room.course_block }}>{{ room.get_course_block_display }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <span><input class="btn btn-default" type="submit" value="Submit"></span>
                </form>

            </div>
        </div>
        <div class="col-md-5">
            <div class="btn-toolbar">
                <button class="btn btn-success" type="submit" id="go">&raquo; Run</button>
                <button class="btn btn-warning" type="submit" id="stop">&raquo; Random Name</button>
                <button class="btn btn-warning" id="freezebutton">Group Size:</button>
                <select class="form-control" type="number" id="freezeGroups" style="max-width:90%;">
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="10">10</option>
                </select>
            </div>
        </div>
        <div class="col-md-4">
                <a class="btn btn-default" href="{% url 'randomizer:classroom' %}" role="button">ADD A CLASS</a>
                <a class="btn btn-default" href="{% url 'randomizer:blocklist' %}" role="button">EDIT A CLASS</a>
                
        </div>
    </div>
  
    <div class="row">
        
        <div class="col-md-1" id="student-column1"></div>
        <div class="col-md-1" id="student-column2"></div>  <!-- anchor element for js -->
        
        <div class="col-md-10">
            <div id="student-choice"></div>  <!-- anchor for student choice -->
        </div>

    </div>


</div>
{% endblock body %}
<div>

{% block extra_js %}
     <script>
    var nameArray = {{ data | safe }};
    console.log(typeof(nameArray))
    console.log(nameArray)
    
    var N = 3; // group size
    var previousGroups = 0;  // # groups of previous freeze
    var moving = false;
    
    var numberStudents = nameArray.length;
    var interval;
    var loopAllowed = false;
    var attend = [];
    var groupMade = false;
    
    for(var n = 0; n < numberStudents; n++) {
        attend[n] = nameArray[n].fields.attend;
        };
    var studentCol1 = document.getElementById('student-column1');
    var studentCol2 = document.getElementById('student-column2');
    var studentChoice = document.getElementById('student-choice');
    var vertGap = 30;
    var divChoice = document.createElement('div');             
    
    var offsetsChoice = document.getElementById('student-choice').getBoundingClientRect();
    var topChoice = offsetsChoice.top;
    var leftChoice = offsetsChoice.left;
    
/*                var offsetsCol = document.getElementById('student-column').getBoundingClientRect();
    var topCol = offsetsCol.top;
    var leftCol = offsetsCol.left;
    console.log(topCol); */
    
    divChoice.id = "choicename";

    divChoice.innerHTML = " ";
    studentChoice.appendChild(divChoice);

    var setNames = function() {
        var h = 0;
        for(var n = 0; n < numberStudents; n++){   <!-- place the names on the screen -->
            var w = 0;
            var divName = "floatName" + n;
            var names = nameArray[n].fields.nickname;
            var divTag = document.createElement('div');
            var divSt1 = document.createElement('div');
            var divSt2 = document.createElement('div');
            divSt1.className = 'col-md-2';
            divSt2.className = 'col-md-2';
            document.body.appendChild(divSt1);
            divTag.id = divName;
            divTag.innerHTML = names;
            divTag.style.position = "absolute";
            if (attend[n] == true) {
                divTag.style.textDecoration = "none";
            } else {
                divTag.style.textDecoration = "line-through";
                divTag.style.color = 'red';
            };
            // w = Math.floor(n/15)*120 - 120;  <!-- shift the columns to the right by 120 -->
            h = n - Math.floor(n/15)*15;  <!-- go back up to the top of the name column -->
            
            divTag.style.top = (10 + h * vertGap) + "px";
            //divTag.style.left  = (0 + w) + "px";
            divTag.style.fontSize = "14px";
            divTag.className = "randomFloat";
            divTag.onclick = boldText;
             
            if (Math.floor(n/15)+1 == 2) {
                studentCol2.appendChild(divTag);
            } else {
                studentCol1.appendChild(divTag);
             <!-- attach to studentCol/'anchor'/parent element -->
            }; 
        };
    };
    setNames();
        
    $( "#go" ).click(function() {
        console.log("it's go time");
        moving = true;
        //clear the previous random name choice if there is one
        var divfc = document.getElementById('choicename');
        console.log(divfc);
        while(divfc.firstChild) {
            divfc.removeChild(divfc.firstChild);
        };
        
        // get the number of kids attending before clearGroups
        group = grouping(N);
        if (groupMade == true) {
            clearGroups(group[0]);
        }

        var gotime = 1;
        interval = setInterval(function () {
            for(var i = 0; i < (numberStudents + 1); i++){
                var divName = "floatName" + i;
                if (attend[i] == true) {
                    $( "#" + divName ).css({
                        left: (Math.random()*500+300) + "px",
                        top: (Math.random()*350 + 40) + "px",
                        "font-size": "20px",
                    });
                };
            };
            gotime += 1;
            if (gotime > 100) {
                clearInterval(interval);
               }
        }, 500);
    });

    $( "#stop" ).click(function() {
        if (moving == true) {
            clearInterval(interval);
            choosePerson(0, numberStudents);
            setTimeout(clearDivs, 1000);
        };
        moving = false;
    });
    
    var clearDivs = function() {
        for(var i = 0; i < (numberStudents); i++) {
            divn = "floatName" + i;
            var elem = document.getElementById(divn);
            elem.remove();
            };
        setNames();
        };
        
    var clearGroups = function() {
        console.log(previousGroups);
        for (i = 0; i < previousGroups; i++) {  //remove the previous # of groups
            num = (i+1);
            var divn = "Group" + num.toString();
            var elem = document.getElementById(divn);
            elem.remove();
            };
        clearDivs();
        groupMade = false;
        }; 
        
        
    function choosePerson (min, max) {
        min = Math.ceil(min);
        max = Math.floor(max);
        var rn = Math.floor(Math.random() * (max - min)) + min;
        if (attend[rn] == false) {
            console.log(rn);
            console.log("choose again");
            return choosePerson(0, numberStudents);
        };
        divChoice.innerHTML = nameArray[rn].fields.nickname;
        divChoice.style.position = "relative";
        divChoice.style.color = "blue";
        divChoice.style.fontWeight = "bold";
        divChoice.style.top = "10px";
        divChoice.style.left = "400px";
        studentChoice.appendChild(divChoice);
        console.log(shuffle(numberStudents));
        };
                          
    function boldText(){
        var togname = this.id.split('floatName').join('');
        console.log(togname);
        var nam = nameArray[togname];
        console.log(nam);
        if (this.style.textDecoration == 'none') {
            this.style.textDecoration = 'line-through';
            this.style.color = 'red';
            attend[togname] = false;
        } else {
            this.style.textDecoration = 'none';
            this.style.color = 'black';
            attend[togname] = true;
        }
        //console.log(attend[togname]);
        };
        
    // knuff-shuffle to mix the list of students
    function shuffle() {
        var array = [];
        for (var n=0; n<numberStudents; n++) {
            array[n-0] = n;
        }
        var currentIndex = array.length
          , temporaryValue
          , randomIndex
          ;

        // While there remain elements to shuffle...
        while (0 !== currentIndex) {

          // Pick a remaining element...
          randomIndex = Math.floor(Math.random() * currentIndex);
          currentIndex -= 1;

          // And swap it with the current element.
          temporaryValue = array[currentIndex];
          array[currentIndex] = array[randomIndex];
          array[randomIndex] = temporaryValue;
        }

        return array;
    }
    
    function grouping(e) {
        var ns = 0;
        // make sure to not count students that are away
        for (n=0; n < numberStudents; n++) {
            if (attend[n] == true) {
                ns++
            };
        };
        
        var extras = ns % e;
        var numGroups = [];
        var totalGroups = 0;
        var threeGroups = Math.floor(ns/e);
        
        if (extras != 0) {
            totalGroups = threeGroups + 1;
        } else {
            totalGroups = threeGroups;
        }
        return [totalGroups, ns]; 
    }
    
    function sort(groupsize) {
        var i = 0;
        var sortName  = [];
        var groupNumbers = [];
        var placeCount = 0;
        var groupDown = 0;
        var groupLeft = 0;
        groupMade = true;
        var studentAttend = 0;
        var leftOver = 0;
        
        // get the random order of students
        var groups = grouping(groupsize);
        console.log(groups[0]);
        console.log(groups[1]);
        previousGroups = groups[0];
        
        // shuffle the order of the students
        var studentOrder = shuffle(nameArray);
        console.log(studentOrder);
        
        // place the group headings
        for (i = 0; i < groups[0]; i++) {
            num = (i+1);
            divGroup = document.createElement('div');
            divGroup.innerHTML = "Group " + num.toString();
            divGroup.id = "Group" + num.toString();
            num = num*120-120;
            divGroup.style.width = "110px";
            divGroup.style.fontSize = "20px";
            divGroup.style.fontWeight = "bold";
            divGroup.style.color = "blue";
            divGroup.style.position = "absolute";
            divGroup.style.top = "100px";
            divGroup.style.left = num.toString() + "px";
            studentCol1.appendChild(divGroup);
        }
        
        // fill each row
        for (i = 0; i < numberStudents; i++) {
            var divName = "floatName" + studentOrder[i];
            var SO = studentOrder[i];
            console.log(document.getElementById(divName).parentNode);
            
            if (attend[SO] == true) {
                var stdId = document.getElementById(divName);
                stdId.parentNode.id = "studentCol1";
                studentCol1.appendChild(stdId);
                studentAttend++;
                stdId.style.fontSize = "20px";
                if (placeCount%groups[0] == 0) {  //check to see if we need a new row
                    groupDown = groupDown + 50;
                    groupLeft = 0;
                }
                $( "#" + divName ).animate({
                    left: ( 00 + groupLeft) + "px",
                    top: (100 + groupDown) + "px"
                }, 300 );
                groupLeft = groupLeft + 120;   // keep moving the names over
                placeCount++;
            } else {
                var stdId = document.getElementById(divName);
                stdId.parentNode.id = "studentCol1";
                studentCol1.appendChild(stdId);
                $("#" + divName ).css({
                    left: leftOver + "px",
                    top: "500px",
                } );
                leftOver = leftOver + 110; 
            }
        } 
    };
    
    $("#freezebutton").on("click", function() {
      let groupNumber = $("#freezeGroups").val();
      if (moving == true) {
            clearInterval(interval);
            setTimeout(sort(groupNumber), 1000);
        }
       moving = false;
      
      console.log("Random Group", groupNumber);
    });                
  
    
</script>
</div>
{% endblock extra_js %}